
import { Category, Product } from './types';

export const COMPANY_INFO = {
  name: 'TST Technologies',
  address: 'Tech Valley, Silicon City',
  phone: '+1 (555) 123-4567',
  email: 'sales@tsttechnologies.com',
  aboutShort: 'Leading provider of advanced security and automation solutions.',
  aboutLong: `TST Technologies has been at the forefront of the security and automation industry since 2003. 
  
  We specialize in biometric systems, access control, entrance automation, and security inspection equipment. Our mission is to provide reliable, high-tech solutions that ensure the safety and efficiency of your operations.
  
  With a global presence and a dedicated R&D team, we continuously innovate to meet the evolving challenges of modern security infrastructure.`
};

// Abstract tech-themed placeholder image (Simulated AI Generation)
export const PLACEHOLDER_IMAGE = "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='800' height='600' viewBox='0 0 800 600'%3E%3Cdefs%3E%3ClinearGradient id='grad1' x1='0%25' y1='0%25' x2='100%25' y2='100%25'%3E%3Cstop offset='0%25' style='stop-color:%23f1f5f9;stop-opacity:1' /%3E%3Cstop offset='100%25' style='stop-color:%23e2e8f0;stop-opacity:1' /%3E%3C/linearGradient%3E%3C/defs%3E%3Crect width='100%25' height='100%25' fill='url(%23grad1)' /%3E%3Cpath d='M400 250 L450 300 L400 350 L350 300 Z' fill='%23cbd5e1' /%3E%3Ccircle cx='400' cy='300' r='80' stroke='%2394a3b8' stroke-width='2' fill='none' /%3E%3Ctext x='50%25' y='60%25' font-family='Inter, sans-serif' font-size='24' fill='%2364748b' text-anchor='middle' dominant-baseline='middle'%3EImage Not Available%3C/text%3E%3C/svg%3E";

export const CATEGORIES: Category[] = [
  {
    id: 'uhf-rfid',
    name: 'UHF RFID Reader',
    description: 'Long-range identification solutions for parking and logistics.',
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/U5-300x300-1.png',
  },
  {
    id: 'canteen',
    name: 'Canteen Management',
    description: 'Automated meal management systems for corporate dining.',
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/LP400-1.png',
  },
  {
    id: 'face',
    name: 'Face Recognition',
    description: 'Advanced facial recognition terminals for secure and hygienic access.',
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/venus.png',
  },
  {
    id: 'finger-print',
    name: 'Finger Print',
    description: 'Biometric fingerprint access control and time attendance systems.',
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/F18.png',
  },
  {
    id: 'flap-barrier',
    name: 'Flap Barrier',
    description: 'Retractable flap barriers for pedestrian access control.',
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/FBTL2000.png',
  },
  {
    id: 'swing-barrier',
    name: 'Swing Barriers',
    description: 'Motorized swing gates for elegant entrance control.',
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/SB-Q-3000.png',
  },
  {
    id: 'guard-patrol',
    name: 'Guard Patrol',
    description: 'Monitoring systems to ensure security personnel patrols.',
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/Fingerprint-Guard-Patrol-1.png',
  },
  {
    id: 'turnstiles',
    name: 'Turnstiles',
    description: 'Tripod and full-height turnstiles for crowd control.',
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/ET1000.png',
  },
  {
    id: 'boom-barrier',
    name: 'Boom Barrier',
    description: 'Automatic vehicle access control barriers.',
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/BG-BDC-RL-100.png',
  },
  {
    id: 'tyre-killer',
    name: 'Tyre Killer',
    description: 'High-security vehicle spikes for hostile vehicle mitigation.',
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/TK-300.png',
  },
  {
    id: 'baggage-scanner',
    name: 'Baggage Scanner',
    description: 'X-Ray inspection systems for luggage and parcel screening.',
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/eBS-5030A.png',
  },
  {
    id: 'metal-detector',
    name: 'Metal Detector',
    description: 'Walk-through and hand-held metal detection units.',
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/D2401.png',
  },
  {
    id: 'elevator-control',
    name: 'Elevator Control',
    description: 'Secure floor access control systems for lifts.',
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/EC10-EX16.png',
  },
  {
    id: 'multi-door',
    name: 'Multi Door Controller',
    description: 'Centralized access control panels for multiple entry points.',
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/inBio-460.png',
  },
  {
    id: 'hotel-lock',
    name: 'Hotel Lock',
    description: 'RFID card locks designed for hospitality.',
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/HL100.png',
  },
  {
    id: '7-series',
    name: '7-Series EM Locks',
    description: 'Electromagnetic locks and buttons (7-Series).',
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/EML600-7-2-1.png',
  },
  {
    id: '8-series',
    name: '8-Series EM Locks',
    description: 'Advanced electromagnetic locks and buttons (8-Series).',
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/EML600-7-5.png',
  },
  {
    id: 'boom-gate',
    name: 'Boom Gate',
    description: 'Heavy-duty gates for industrial traffic management.',
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/BG-BDC-RL-100.png',
  }
];

export const PRODUCTS: Product[] = [
  {
    id: '287',
    categoryId: 'uhf-rfid',
    name: 'KR 500 E',
    shortDescription: '125 KHz Proximity card reader with up to 10CM read range.',
    fullDescription: `KR500E is a robust 125 KHz Proximity card reader designed for durability and performance. Features include a read range of up to 10CM, Wiegand connectivity, and IP68 waterproof ABS case.`,
    price: 'Request Quote',
    features: ['Reading Range : 3-8cm', 'Humidity : 10% to 90% RH', 'Door Opening Time : 0-99s', 'IP68 Waterproof'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/08/KR500-E-2.png',
    specifications: { 'Dimensions': '109*47*20mm', 'Power': 'DC 6-14V / Max.70mA' }
  },
  {
    id: '428',
    categoryId: 'uhf-rfid',
    name: 'JS-500E',
    shortDescription: 'Waterproof IP68 Multi-function RFID reader.',
    fullDescription: `The JS-500E is a versatile RFID reader supporting EM/HD cards. It features an ABS case, IP68 waterproof rating, and WG26/34 output.`,
    price: 'Request Quote',
    features: ['Card type : EM/HD', 'Working voltage : DC12V+10%', 'Reading Range : 3-8cm'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/JS-500E-2.png',
    specifications: { 'Dimensions': '109*47*20mm', 'Humidity': '10% to 90% RH' }
  },
  {
    id: '433',
    categoryId: 'uhf-rfid',
    name: 'U-5',
    shortDescription: 'UHF Middle Range Integrated RFID Reader.',
    fullDescription: `High performance UHF reader supporting ISO18000-6C protocol. Features adjustable RF power and high sensitivity for reliable detection.`,
    price: 'Request Quote',
    features: ['Frequency: 902-928MHz (US), 865-868MHz (EU)', 'Protocol: ISO18000-6C, EPC G2', 'RF Power: 0-31dBm adjustable'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/U5-300x300-1.png',
    specifications: { 'Dimension': '280 x 280 x 68.5 mm', 'Working Temp': '-20°C ~ 60°C' }
  },
  {
    id: '436',
    categoryId: 'uhf-rfid',
    name: 'KR503-M',
    shortDescription: '13.56MHz Mifare card reader with RS485.',
    fullDescription: `Compact Mifare card reader with RS485 communication. Ideal for secure access control applications requiring fast reading times.`,
    price: 'Request Quote',
    features: ['Read Range: Up to 5CM', 'Communication: RS485', 'Reading Time: ≤300ms'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/KR503-M.png',
    specifications: { 'Dimension': '116 x 75 x 17.3mm', 'Power': 'DC 6-14V / Max.70mA' }
  },
  {
    id: '439',
    categoryId: 'uhf-rfid',
    name: 'KR503-E',
    shortDescription: '125KHz Proximity card reader with RS485.',
    fullDescription: `Reliable proximity card reader featuring RS485 communication and a read range of up to 10cm. Includes LED indicators and beeper.`,
    price: 'Request Quote',
    features: ['Read Range: Up to 10CM', 'Communication: RS485', 'IP65 Protection'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/KR503-E.png',
    specifications: { 'Dimension': '116 x 75 x 17.3mm', 'Operating Temp': '-20°C to +65°C' }
  },
  {
    id: '442',
    categoryId: 'uhf-rfid',
    name: 'KR500-M',
    shortDescription: '13.56 MHz Mifare card reader.',
    fullDescription: `Mifare card reader with Wiegand connectivity. Compact design suitable for various architectural styles.`,
    price: 'Request Quote',
    features: ['Read Range: Up to 5CM', 'Connectivity: Wiegand', 'Reading Time: ≤200ms'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/KR500-M.png',
    specifications: { 'Weight': '50g', 'Power': 'DC 6-14V' }
  },
  {
    id: '445',
    categoryId: 'uhf-rfid',
    name: 'SA32-M',
    shortDescription: 'Standalone Access Control with Smart Card.',
    fullDescription: `Standalone device supporting Card, PIN, or Card & PIN access. Includes relay output and doorbell port.`,
    price: 'Request Quote',
    features: ['Storage: 1000 users', 'Operating voltage: DC 12V', 'Card Reading Distance: 1-15CM'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/SA32-M.png',
    specifications: { 'Dimensions': '121x78x23mm', 'Weight': '110g' }
  },
  {
    id: '449',
    categoryId: 'uhf-rfid',
    name: 'SA32-E',
    shortDescription: 'Standalone Access Control Device.',
    fullDescription: `Robust standalone access control supporting 1000 users. Features multiple access modes and durable construction.`,
    price: 'Request Quote',
    features: ['Access by Card, PIN, or Both', '1 Relay output', 'Doorbell Port'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/SA32-E.png',
    specifications: { 'Dimensions': '121x78x23mm', 'Storage': '1000 users' }
  },
  {
    id: '455',
    categoryId: 'uhf-rfid',
    name: 'JS-32E (PROXIMITY)',
    shortDescription: 'Proximity Standalone Access Control.',
    fullDescription: `Standalone access control unit with keypad and proximity reader. Supports 2000 users and Wiegand 26 input/output.`,
    price: 'Request Quote',
    features: ['Capacity: 2000 users', 'Access Way: Pin, Card, Pin+Card', 'Wiegand 26 I/O'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/js32.png',
    specifications: { 'Dimensions': '115*75*16mm', 'Reading Range': '3-8cm' }
  },
  {
    id: '459',
    categoryId: 'uhf-rfid',
    name: 'JS-500M',
    shortDescription: 'Mifare Card Reader with IP68 Waterproof.',
    fullDescription: `Durable Mifare reader with ABS case and IP68 waterproof rating. Suitable for outdoor installation.`,
    price: 'Request Quote',
    features: ['Waterproof IP68', 'WG26/34 Output', 'Short-circuit Protect'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/JS-500E-2.png',
    specifications: { 'Dimensions': '109*47*20mm', 'Working Voltage': 'DC12V' }
  },
  {
    id: '460',
    categoryId: 'uhf-rfid',
    name: 'SA40',
    shortDescription: 'Standalone Access Control supporting RFID & Password.',
    fullDescription: `Versatile access control device supporting 2000 users. Features password and card verification modes.`,
    price: 'Request Quote',
    features: ['User Capacity: 2000', 'Password Capacity: 2000', 'Verification: Card/Password'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/SA40.png',
    specifications: { 'Dimensions': '103.5*86*19mm', 'Frequency': '125kHz / 13.56MHz' }
  },
  {
    id: '465',
    categoryId: 'uhf-rfid',
    name: 'S990',
    shortDescription: 'Standalone RFID Time Attendance & Access Control.',
    fullDescription: `Comprehensive time attendance system with 30,000 card capacity. Supports WiFi/GPRS and features a 2.8-inch TFT display.`,
    price: 'Request Quote',
    features: ['Card Storage: 30,000', 'Transaction Capacity: 100,000', 'Communication: TCP/IP, RS232/485, WiFi'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/S990A-removebg-preview.png',
    specifications: { 'Dimensions': '210x157x40mm', 'CPU': '32 bit 800MHz' }
  },
  {
    id: '468',
    categoryId: 'uhf-rfid',
    name: 'SC-403-ID',
    shortDescription: 'Proximity T&A System with Access Control.',
    fullDescription: `Efficient time attendance system with access control capabilities. Supports 30,000 cards and 50,000 logs.`,
    price: 'Request Quote',
    features: ['Read Range: 8-10cm', 'Access Control Functionality', 'Users: 30,000 Cards'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/Sc503.png',
    specifications: { 'Dimensions': '143x95.5x39.5mm', 'Communication': 'TCP/IP, RS232/485' }
  },
  {
    id: '470',
    categoryId: 'uhf-rfid',
    name: 'UR10RW-F',
    shortDescription: 'UHF Card Issuer / Reader.',
    fullDescription: `Desktop UHF reader/writer for card issuance. Supports encrypted UHF tags and keyboard emulation output.`,
    price: 'Request Quote',
    features: ['Encrypted UHF Tag Support', 'USB Analog Keyboard Output', 'Read Distance: 20-40cm'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/UR10R-1E-and-UR10R-1F.png',
    specifications: { 'Dimensions': '107*107*23mm', 'Frequency': '865-868MHz / 902-928MHz' }
  },
  {
    id: '473',
    categoryId: 'uhf-rfid',
    name: 'U-10',
    shortDescription: 'UHF Middle Range Integrated RFID Reader.',
    fullDescription: `Long-range UHF reader with 12dBi antenna for superior sensitivity. Ideal for vehicle access control.`,
    price: 'Request Quote',
    features: ['Protocol: ISO18000-6C', 'RF Power: 0-31dBm Adjustable', 'Sensitivity: -80dBm'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/U10.png',
    specifications: { 'Dimension': '440x440x68.6mm', 'Processor': 'ARM Cortex M3' }
  },
  {
    id: '475',
    categoryId: 'canteen',
    name: 'LP400',
    shortDescription: 'Canteen Management System with Thermal Printer.',
    fullDescription: `Specialized canteen management terminal with built-in thermal printer. Supports fingerprint verification and meal tracking.`,
    price: 'Request Quote',
    features: ['Built-in Thermal Printer', '3000 Templates', '100,000 Transactions', '3-inch TFT Screen'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/LP400-1.png',
    specifications: { 'Dimensions': '171x284x120mm', 'Power': '12V DC 3A' }
  },
  {
    id: '479',
    categoryId: 'face',
    name: 'FACE – AIFACE-VENUS',
    shortDescription: 'Visible Light Facial Recognition Terminal.',
    fullDescription: `Advanced facial recognition with 5-inch touch screen. Features anti-spoofing algorithm and wide pose angle acceptance.`,
    price: 'Request Quote',
    features: ['Face Capacity: 6000', 'Visible Light Recognition', 'Anti-spoofing', 'WiFi Optional'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/venus.png',
    specifications: { 'Dimensions': '100*203.3*24.5mm', 'OS': 'Linux' }
  },
  {
    id: '482',
    categoryId: 'face',
    name: 'SFACE900',
    shortDescription: 'Multi-Biometric Time Attendance Terminal.',
    fullDescription: `Versatile terminal supporting face and fingerprint verification. 4.3-inch touch screen for intuitive operation.`,
    price: 'Request Quote',
    features: ['Face Capacity: 3000', 'Fingerprint Capacity: 4000', 'Backup Battery Optional'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/SFace900.png',
    specifications: { 'Dimensions': '195.5*166.5*120mm', 'Display': '4.3-Inch Touch' }
  },
  {
    id: '487',
    categoryId: 'face',
    name: 'UFACE-301',
    shortDescription: 'Multi-Biometric Access Control System.',
    fullDescription: `Face and ID card time attendance system. High verification speed and advanced UI.`,
    price: 'Request Quote',
    features: ['Face Capacity: 3000', 'ID Card Capacity: 10,000', 'Push Data Support'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/uFace301.png',
    specifications: { 'Dimensions': '193.6x165.2x86mm', 'Comm': 'TCP/IP, RS232/485' }
  },
  {
    id: '490',
    categoryId: 'face',
    name: 'FACE – MB20',
    shortDescription: 'Hybrid Biometric Time Attendance Terminal.',
    fullDescription: `Compact device with Face, Fingerprint, RFID and Password verification. Supports 500 faces and 1000 users.`,
    price: 'Request Quote',
    features: ['Face Capacity: 500', 'Fingerprint Capacity: 2000', 'TCP/IP Connectivity'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/mb20.png',
    specifications: { 'Dimensions': '161.93x152.82x30.59mm', 'Power': 'DC 5V 0.8A' }
  },
  {
    id: '495',
    categoryId: 'face',
    name: 'FACE – MB160',
    shortDescription: 'Multi-Bio Time Attendance with Access Control.',
    fullDescription: `Supports 1500 faces and 2000 fingerprints. Professional firmware with flexible features.`,
    price: 'Request Quote',
    features: ['Face Capacity: 1500', 'Verification Speed: ≤0.5 Sec', 'Access Control Interface'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/mb160.png',
    specifications: { 'Dimensions': '167.5x148.8x32.2mm', 'Power': 'DC 12V 1.5A' }
  },
  {
    id: '498',
    categoryId: 'face',
    name: 'FACE – SILKBIO-101TC',
    shortDescription: 'Face & Fingerprint Terminal with SilkID.',
    fullDescription: `Features SilkID fingerprint sensor for wet/dry finger detection and face recognition. 2000 face capacity.`,
    price: 'Request Quote',
    features: ['Face Capacity: 2000', 'SilkID Sensor', 'Built-in Battery'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/silkbio101tc.png',
    specifications: { 'Dimensions': '180x154x34.2mm', 'Display': '2.8 inch TFT' }
  },
  {
    id: '500',
    categoryId: 'face',
    name: 'FACE – UFACE-302',
    shortDescription: 'Multi-Biometric T&A and Access Control.',
    fullDescription: `High capacity terminal with 3000 faces and 4000 fingerprints. 4.3-inch touch screen.`,
    price: 'Request Quote',
    features: ['Face Capacity: 3000', 'Fingerprint Capacity: 4000', 'Battery Backup Optional'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/uFace-302.png',
    specifications: { 'Dimensions': '193.6x165.2x86mm', 'Comm': 'TCP/IP, WiFi' }
  },
  {
    id: '502',
    categoryId: 'face',
    name: 'FACE – EFACE-990',
    shortDescription: 'High Capacity Facial Recognition System.',
    fullDescription: `Supports up to 6000 faces and 10,000 fingerprints. Powerful CPU for fast matching.`,
    price: 'Request Quote',
    features: ['Face Capacity: 6000', 'Fingerprint Capacity: 10,000', '1.2GHz CPU'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/eFace-990.png',
    specifications: { 'Display': '4.3 Inch Touch', 'Memory': '1GB RAM' }
  },
  {
    id: '504',
    categoryId: 'face',
    name: 'FACE – AIFACE-JUPITER',
    shortDescription: 'Outdoor Visible Light Facial Recognition.',
    fullDescription: `Robust outdoor terminal with 5-inch screen. IP65 rated for water and dust resistance.`,
    price: 'Request Quote',
    features: ['Face Capacity: 6,000', 'IP65 Water Resistant', 'Visible Light Recognition'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/AiFace-Jupiter.png',
    specifications: { 'Dimensions': '134.93*166.93*21.5mm', 'OS': 'Linux' }
  },
  {
    id: '506',
    categoryId: 'face',
    name: 'FACE – AIFACE-URANUS',
    shortDescription: 'Compact Facial Recognition Terminal.',
    fullDescription: `Sleek design with 2.8-inch screen. Supports 500 faces and 2000 fingerprints.`,
    price: 'Request Quote',
    features: ['Face Capacity: 500', 'Fingerprint Capacity: 2000', 'Stereo Speaker'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/Uranus.png',
    specifications: { 'Dimensions': '167.9x151.5x30mm', 'Power': 'DC 5V 0.8A' }
  },
  {
    id: '509',
    categoryId: 'face',
    name: 'FACE – AIFACE-VENUS',
    shortDescription: 'Visible Light Facial Recognition (Venus).',
    fullDescription: `Efficient visible light facial recognition with 500 face capacity. Compact 4.3-inch touch screen.`,
    price: 'Request Quote',
    features: ['Face Capacity: 500', 'User Capacity: 1,000', 'Visible Light Recognition'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/Neptune.png',
    specifications: { 'Dimensions': '130*119*28mm', 'Speed': '≤1s' }
  },
  {
    id: '512',
    categoryId: 'face',
    name: 'FACE – AIFACE- MERCURY',
    shortDescription: 'WiFi Enabled Facial Recognition.',
    fullDescription: `WiFi-ready terminal with 800 face capacity. 2.8-inch touch screen and WDR camera.`,
    price: 'Request Quote',
    features: ['Face Capacity: 800', 'WiFi Connectivity', 'WDR Low Light Camera'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/venus-1.png',
    specifications: { 'Dimensions': '100*100.2*23.7mm', 'Power': '5V/2A' }
  },
  {
    id: '514',
    categoryId: 'face',
    name: 'FACE – AIFACE-PLUTO',
    shortDescription: '4-inch Touch Screen Facial Terminal.',
    fullDescription: `Supports 1000 faces and cards. Dual core CPU for fast processing.`,
    price: 'Request Quote',
    features: ['Face Capacity: 1000', '4-inch Touch Screen', 'Linux OS'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/venus-2.png',
    specifications: { 'Dimensions': '72.94*157.94*23mm', 'Weight': '260g' }
  },
  {
    id: '516',
    categoryId: 'face',
    name: 'FACE – AIFACE-MARS',
    shortDescription: '5-inch Touch Screen Facial System.',
    fullDescription: `High performance terminal with 3000 face capacity. Supports WiFi and various card modules.`,
    price: 'Request Quote',
    features: ['Face Capacity: 3000', '5-inch Touch Screen', 'WiFi Optional'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/mars.png',
    specifications: { 'Dimensions': '91.93*202.93*21.5mm', 'OS': 'Linux' }
  },
  {
    id: '518',
    categoryId: 'face',
    name: 'FACE – MU-AI-9',
    shortDescription: 'Compact AI Face Recognition Module.',
    fullDescription: `Embedded AI face recognition with 50,000 face capacity. 2.8 inch screen.`,
    price: 'Request Quote',
    features: ['Face Capacity: 50,000', 'Transactions: 50,000', 'IR Fill Light'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/MU-AI-9.png',
    specifications: { 'Dimensions': '94x94x17mm', 'WiFi': 'Support 2.4ghz' }
  },
  {
    id: '521',
    categoryId: 'face',
    name: 'FACE – AIFACE MAGNUM',
    shortDescription: 'IP65 Weatherproof Facial Terminal.',
    fullDescription: `Outdoor ready with IP65 rating. Supports 1500 faces and 5000 fingerprints.`,
    price: 'Request Quote',
    features: ['IP65 Rated', 'Face Capacity: 1500', 'Fingerprint Capacity: 5000'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/Aiface-Magnum.png',
    specifications: { 'Dimensions': '185*58.5*20mm', 'Temp': '-5°C to 45°C' }
  },
  {
    id: '523',
    categoryId: 'face',
    name: 'EYEFACE-99',
    shortDescription: 'Multimodal Iris & Face Recognition.',
    fullDescription: `Advanced multimodal recognition with iris and face scanning. 50,000 face capacity.`,
    price: 'Request Quote',
    features: ['Face Capacity: 50,000', 'Iris Recognition', 'Temp Measurement'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/EyeFace-99.png',
    specifications: { 'Camera': '800x1280', 'Comm': 'WiFi, TCP/IP' }
  },
  {
    id: '525',
    categoryId: 'finger-print',
    name: 'FINGERPRINT – LP400',
    shortDescription: 'Fingerprint T&A with Thermal Printer.',
    fullDescription: `Fingerprint time attendance with built-in thermal printer. 3000 template capacity.`,
    price: 'Request Quote',
    features: ['Built-in Thermal Printer', '3000 Templates', 'Battery Backup'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/LP400.png',
    specifications: { 'Dimensions': '171x284x120mm', 'Screen': '3 inch TFT' }
  },
  {
    id: '527',
    categoryId: 'finger-print',
    name: 'FINGERPRINT – ICLOCK990',
    shortDescription: 'High Capacity Fingerprint System.',
    fullDescription: `Enterprise grade fingerprint system with 40,000 user capacity. 3.5 inch TFT display.`,
    price: 'Request Quote',
    features: ['Users: 40,000', 'Fingerprint Capacity: 40,000', 'Push Data Inbuilt'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/iClock-990.png',
    specifications: { 'Dimensions': '210x157x40mm', 'Power': 'DC 12V 3A' }
  },
  {
    id: '529',
    categoryId: 'finger-print',
    name: 'FINGERPRINT – F18',
    shortDescription: 'Access Control Reader with LCD.',
    fullDescription: `Compact fingerprint reader for access control. 3000 fingerprint capacity.`,
    price: 'Request Quote',
    features: ['Fingerprint Capacity: 3000', 'Access Control Interface', 'TCP/IP, RS485'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/F18.png',
    specifications: { 'Dimensions': '183x80x42mm', 'Power': 'DC 12V 1.5A' }
  },
  {
    id: '531',
    categoryId: 'finger-print',
    name: 'FINGER PRINT – X990',
    shortDescription: 'Standalone Fingerprint T&A System.',
    fullDescription: `Popular standalone fingerprint time attendance. 10,000 fingerprint capacity.`,
    price: 'Request Quote',
    features: ['Fingerprint Capacity: 10,000', 'Battery Backup', 'WiFi/GPRS Optional'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/x990.png',
    specifications: { 'Dimensions': '210x157x40mm', 'Display': '3 Inch Color TFT' }
  },
  {
    id: '533',
    categoryId: 'finger-print',
    name: 'FINGERPRINT – F22',
    shortDescription: 'Ultra Thin Fingerprint Terminal.',
    fullDescription: `Sleek design with SilkID sensor. WiFi enabled for easy connectivity.`,
    price: 'Request Quote',
    features: ['Fingerprint Capacity: 3000', 'Built-in WiFi', 'SilkID Sensor'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/F22.png',
    specifications: { 'Dimensions': '158.5x78.0x19.4mm', 'Power': 'DC 12V 1.5A' }
  },
  {
    id: '535',
    categoryId: 'finger-print',
    name: 'FINGERPRINT – SF100',
    shortDescription: 'IP Based Fingerprint Access Control.',
    fullDescription: `Compact IP based fingerprint terminal. 1500 fingerprint capacity.`,
    price: 'Request Quote',
    features: ['Fingerprint Capacity: 1500', 'TCP/IP, RS485', 'Wiegand Output'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/SF100.png',
    specifications: { 'Dimensions': '90x90x34.5mm', 'Display': '2.4 TFT' }
  },
  {
    id: '537',
    categoryId: 'finger-print',
    name: 'FINGER PRINT – K30 PRO',
    shortDescription: 'Simple Fingerprint T&A Terminal.',
    fullDescription: `Entry level fingerprint time attendance. 2000 user capacity with battery backup.`,
    price: 'Request Quote',
    features: ['User Capacity: 2000', 'Inbuilt Battery', 'SSR Recorder'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/K30.png',
    specifications: { 'Dimensions': '185x140x30mm', 'Power': '12V DC 1.5A' }
  },
  {
    id: '540',
    categoryId: 'finger-print',
    name: 'FINGERPRINT EXIT READER-FR1200',
    shortDescription: 'Slave Fingerprint Reader.',
    fullDescription: `RS485 slave reader for capturing fingerprints. IP65 rated for outdoor use.`,
    price: 'Request Quote',
    features: ['RS485 Communication', 'IP65 Waterproof', 'Compact Design'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/FR1200.png',
    specifications: { 'Dimensions': '48x100x37mm', 'Temp': '0°C - 45°C' }
  },
  {
    id: '542',
    categoryId: 'finger-print',
    name: 'FINGERPRINT – X7',
    shortDescription: 'Standalone Biometric Keypad.',
    fullDescription: `Innovative biometric fingerprint reader for access control applications. Simple and reliable.`,
    price: 'Request Quote',
    features: ['Fingerprint Capacity: 500', 'Card Capacity: 500', 'Electric Lock Support'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/x7.png',
    specifications: { 'Dimensions': '88x88x35mm', 'Power': '12V DC 3A' }
  },
  {
    id: '544',
    categoryId: 'finger-print',
    name: 'P160',
    shortDescription: 'Multi-Biometric with Palm Recognition.',
    fullDescription: `Advanced terminal supporting Palm and Fingerprint recognition. 600 palm capacity.`,
    price: 'Request Quote',
    features: ['Palm Capacity: 600', 'Fingerprint Capacity: 3000', 'POE Optional'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/P160.png',
    specifications: { 'Dimensions': '179.95x134.94x38.5mm', 'Display': '2.8-inch TFT' }
  },
  {
    id: '546',
    categoryId: 'finger-print',
    name: 'SILK-FP-101TA',
    shortDescription: 'SilkID Time Attendance System.',
    fullDescription: `Time attendance terminal featuring SilkID sensor for superior performance with dry/wet fingers.`,
    price: 'Request Quote',
    features: ['Fingerprint Capacity: 3000', 'SilkID Sensor', 'USB Host & Client'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/SilkFP-101TA.png',
    specifications: { 'Dimensions': '192x140x42.5mm', 'Power': 'DC 5V' }
  },
  {
    id: '548',
    categoryId: 'finger-print',
    name: 'WL20',
    shortDescription: 'Wireless Time Attendance Terminal.',
    fullDescription: `WiFi enabled fingerprint terminal. Ideal for small offices without network cabling.`,
    price: 'Request Quote',
    features: ['Fingerprint Capacity: 1000', 'WiFi Standard', 'SSR Excel Reports'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/WL20.png',
    specifications: { 'Dimensions': '165x133x21mm', 'Power': 'DC 5V' }
  },
  {
    id: '550',
    categoryId: 'finger-print',
    name: 'UA300',
    shortDescription: '3-inch Screen Fingerprint Terminal.',
    fullDescription: `User friendly time attendance with 3 inch screen. 3000 fingerprint capacity.`,
    price: 'Request Quote',
    features: ['Fingerprint Capacity: 3000', 'Webserver', 'TCP/IP USB'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/ua300.png',
    specifications: { 'Dimensions': '180x135x37mm', 'Power': '5V DC 2A' }
  },
  {
    id: '552',
    categoryId: 'finger-print',
    name: 'U460',
    shortDescription: 'Fingerprint T&A with Access Control.',
    fullDescription: `Reliable fingerprint system for time attendance and simple access control.`,
    price: 'Request Quote',
    features: ['Users: 2,200', 'Access Control Interface', 'TCP/IP'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/u460.png',
    specifications: { 'Dimensions': '189x136x44mm', 'Sensor': '500 DPI Optical' }
  },
  {
    id: '554',
    categoryId: 'finger-print',
    name: 'MA500',
    shortDescription: 'Outdoor Fingerprint Access Control.',
    fullDescription: `Robust IP65 rated fingerprint reader for outdoor access control. Metal casing.`,
    price: 'Request Quote',
    features: ['IP65 Waterproof', 'Metal Casing', 'RS485 & TCP/IP'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/MA500.png',
    specifications: { 'Dimensions': '83x127.5x74mm', 'Power': '12V DC' }
  },
  {
    id: '556',
    categoryId: 'finger-print',
    name: 'ICLOCK360',
    shortDescription: 'High Capacity Fingerprint T&A.',
    fullDescription: `Supports 8000 fingerprints. Feature rich time attendance terminal.`,
    price: 'Request Quote',
    features: ['Users: 8000', '3.5 inch TFT Screen', 'TCP/IP'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/iClock360-.png',
    specifications: { 'Dimensions': '190x140x46mm', 'Power': '12V DC' }
  },
  {
    id: '558',
    categoryId: 'finger-print',
    name: 'F6',
    shortDescription: 'Standalone Fingerprint Access Control.',
    fullDescription: `Compact standalone fingerprint reader for door control. RS485 interface.`,
    price: 'Request Quote',
    features: ['Fingerprint Capacity: 500', 'RS485', 'Access Control Interface'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/F6.png',
    specifications: { 'Sensor': '500 DPI Optical', 'Comm': 'RS485, SD Card' }
  },
  {
    id: '560',
    categoryId: 'finger-print',
    name: 'E9C WI-FI',
    shortDescription: 'WiFi Fingerprint T&A.',
    fullDescription: `Fingerprint time attendance with built-in WiFi. Easy installation.`,
    price: 'Request Quote',
    features: ['WiFi, TCP/IP, USB', 'Push Data Standard', 'Color TFT'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/iClock-990-1.png',
    specifications: { 'Dimensions': '213x149x46mm', 'Power': '5V DC 2A' }
  },
  {
    id: '562',
    categoryId: 'finger-print',
    name: 'K21 PRO',
    shortDescription: 'SSR Fingerprint Recorder.',
    fullDescription: `Self Service Recorder (SSR) time attendance terminal. Generates reports directly.`,
    price: 'Request Quote',
    features: ['Fingerprint Capacity: 800', 'SSR Excel Reports', 'Battery Backup'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/k21.png',
    specifications: { 'Dimensions': '185x138x45mm', 'Power': '5V DC' }
  },
  {
    id: '564',
    categoryId: 'flap-barrier',
    name: 'FB-TL-119',
    shortDescription: 'Single Lane Flap Barrier.',
    fullDescription: `Efficient flap barrier for pedestrian control. Smooth operation and durable SUS304 housing.`,
    price: 'Request Quote',
    features: ['Throughput: 35 p/m', 'SUS304 Stainless Steel', 'Anti-clipping function'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/FBTL119.png',
    specifications: { 'Dimensions': '800x280x960mm', 'Passage Width': '≤ 550mm' }
  },
  {
    id: '566',
    categoryId: 'flap-barrier',
    name: 'FB-TL-2200',
    shortDescription: 'Luxury Flap Barrier.',
    fullDescription: `High-end flap barrier with acrylic wings and LED indicators. Suitable for corporate lobbies.`,
    price: 'Request Quote',
    features: ['SUS304 Stainless Steel', 'LED Indicator', 'MCBF: 2 million'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/FBTL2200.png',
    specifications: { 'Dimensions': '1200x280x980mm', 'Lane Width': '550mm' }
  },
  {
    id: '568',
    categoryId: 'flap-barrier',
    name: 'FB-TL-2000',
    shortDescription: 'Standard Flap Barrier.',
    fullDescription: `Reliable flap barrier for high traffic areas. Retracting barrier movement.`,
    price: 'Request Quote',
    features: ['Retracting Barrier', 'Emergency Mode', 'Indoor/Outdoor'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/FBTL2000.png',
    specifications: { 'Dimensions': '1200x280x980mm', 'Net Weight': '100kg' }
  },
  {
    id: '570',
    categoryId: 'flap-barrier',
    name: 'FB-TL-219-(900MM)',
    shortDescription: 'Wide Lane Flap Barrier.',
    fullDescription: `Wide passage (900mm) flap barrier for wheelchair access or luggage.`,
    price: 'Request Quote',
    features: ['Passage Width: 900mm', 'Throughput: 35 p/m', 'Anti-clipping'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/fbtl219900mm.png',
    specifications: { 'Power': '30W', 'Voltage': '24V' }
  },
  {
    id: '572',
    categoryId: 'flap-barrier',
    name: 'FB-TL-119-(900MM)',
    shortDescription: 'Wide Lane Flap Barrier 119.',
    fullDescription: `Single lane wide passage flap barrier. Ideal for accessible entrances.`,
    price: 'Request Quote',
    features: ['Passage Width: 900mm', 'SUS304 Housing', 'DC Drive'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/fbtl119900mm.png',
    specifications: { 'Dimensions': '800x280x960mm', 'Throughput': '35 p/m' }
  },
  {
    id: '575',
    categoryId: 'flap-barrier',
    name: 'FB-TL-219',
    shortDescription: 'Compact Flap Barrier.',
    fullDescription: `Compact design for tight spaces. Reliable performance and elegant look.`,
    price: 'Request Quote',
    features: ['Passage Width: 550mm', 'Throughput: 35 p/m', 'Bi-directional'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/FBTL219.png',
    specifications: { 'Dimensions': '800x280x960mm', 'Power': '30W' }
  },
  {
    id: '576',
    categoryId: 'flap-barrier',
    name: 'FB-E-2000 SERIES',
    shortDescription: 'Economic Flap Barrier Series.',
    fullDescription: `Cost effective flap barrier solution. Durable and efficient for mass transit.`,
    price: 'Request Quote',
    features: ['MCBF: 3 Million', 'IP44 Rating', 'Acrylic Barrier'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/FB-E-2000.png',
    specifications: { 'Dimensions': '1200x280x980mm', 'Weight': '52kg' }
  },
  {
    id: '578',
    categoryId: 'flap-barrier',
    name: 'FB-E-2200',
    shortDescription: 'Enhanced Economic Flap Barrier.',
    fullDescription: `Upgraded economic series with better finish and durability.`,
    price: 'Request Quote',
    features: ['MCBF: 3 Million', 'LED Indicator', 'Emergency Mode'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/FB-E-2200-1.png',
    specifications: { 'Dimensions': '1200x280x980mm', 'Pass Width': '550mm' }
  },
  {
    id: '581',
    categoryId: 'flap-barrier',
    name: 'FB-Y-1000',
    shortDescription: 'Single Lane Flap Barrier.',
    fullDescription: `High performance flap barrier with brushless motor. 5 million MCBF.`,
    price: 'Request Quote',
    features: ['Brushless Motor', 'MCBF: 5 Million', '6 Pairs Sensors'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/fb-y-1000-removebg-preview.png',
    specifications: { 'Dimensions': '1400*280*950mm', 'IP Rating': '56' }
  },
  {
    id: '583',
    categoryId: 'flap-barrier',
    name: 'FB-Y-1200',
    shortDescription: 'Multi-Lane Flap Barrier.',
    fullDescription: `Designed for multi-lane configurations. Smooth and quiet operation.`,
    price: 'Request Quote',
    features: ['Brushless Motor', 'MCBF: 5 Million', 'Anti-tail function'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/FB-Y-1200-removebg-preview.png',
    specifications: { 'Dimensions': '1400*280*950mm', 'Pass Width': '550mm' }
  },
  {
    id: '585',
    categoryId: 'swing-barrier',
    name: 'SB-TL-129',
    shortDescription: 'Swing Barrier Gate.',
    fullDescription: `Swing barrier with acrylic arms. Suitable for bidirectional traffic.`,
    price: 'Request Quote',
    features: ['Throughput: 30 p/m', 'Bi-directional', 'Anti-clipping'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/SB-TL-129.png',
    specifications: { 'Dimensions': '800x480x980mm', 'Pass Width': '550mm' }
  },
  {
    id: '587',
    categoryId: 'swing-barrier',
    name: 'SB-Q-3200(900MM)',
    shortDescription: 'Wide Lane Swing Barrier.',
    fullDescription: `Wide lane swing barrier for handicapped access. Elegant design.`,
    price: 'Request Quote',
    features: ['Pass Width: 600-900mm', 'Throughput: 40 p/m', 'IP54'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/sb-q-3200-900mm.png',
    specifications: { 'Dimensions': '1400x185x1020mm', 'Net Weight': '99kg' }
  },
  {
    id: '589',
    categoryId: 'swing-barrier',
    name: 'SB-Q-3000(900MM)',
    shortDescription: 'Premium Wide Swing Barrier.',
    fullDescription: `Premium swing barrier with 900mm passage. High throughput.`,
    price: 'Request Quote',
    features: ['Pass Width: 900mm', 'Throughput: 40 p/m', 'IP54'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/sb-q-3000-900mm.png',
    specifications: { 'Dimensions': '1400x185x1020mm', 'Power': '50W' }
  },
  {
    id: '591',
    categoryId: 'swing-barrier',
    name: 'SB-Q-3200',
    shortDescription: 'Standard Swing Barrier.',
    fullDescription: `Reliable swing barrier for standard width passage. Stainless steel body.`,
    price: 'Request Quote',
    features: ['Pass Width: 600mm', 'Throughput: 40 p/m', 'IP54'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/SBQ3200_1.png',
    specifications: { 'Dimensions': '1400x185x1020mm', 'Net Weight': '99kg' }
  },
  {
    id: '593',
    categoryId: 'swing-barrier',
    name: 'SB-Q-3000',
    shortDescription: 'Classic Swing Barrier.',
    fullDescription: `Classic design swing barrier. Efficient for high traffic zones.`,
    price: 'Request Quote',
    features: ['Pass Width: 600mm', 'Throughput: 40 p/m', 'IP54'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/SBQ3000.png',
    specifications: { 'Dimensions': '1400x185x1020mm', 'Power': '50W' }
  },
  {
    id: '595',
    categoryId: 'swing-barrier',
    name: 'SB-ES-3012-2',
    shortDescription: 'Fast Swing Barrier.',
    fullDescription: `Fast operating swing barrier (0.2s). Brushed motor drive.`,
    price: 'Request Quote',
    features: ['Operating Time: 0.2s', 'MCBF: 5 Million', '4 Pairs Infrared'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/SB-ES-3012-2New.png',
    specifications: { 'Dimensions': '1200*185*980mm', 'Pass Width': '600mm' }
  },
  {
    id: '597',
    categoryId: 'swing-barrier',
    name: 'SB-ES-3012',
    shortDescription: 'Efficient Swing Barrier.',
    fullDescription: `Efficient and durable swing barrier. 5 million cycles MCBF.`,
    price: 'Request Quote',
    features: ['Operating Time: 0.2s', 'MCBF: 5 Million', 'Transparent Acrylic Arm'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/SB-ES-3012-removebg-preview.png',
    specifications: { 'Dimensions': '1200*185*980mm', 'Pass Width': '600mm' }
  },
  {
    id: '599',
    categoryId: 'swing-barrier',
    name: 'SB-Q-4000',
    shortDescription: 'Advanced Swing Barrier.',
    fullDescription: `Advanced swing barrier with multiple control modes. Precise positioning sensors.`,
    price: 'Request Quote',
    features: ['Unlock Time: 0.2s', 'Throughput: 35 p/m', 'Multiple Control Modes'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/SB-Q-4000.png',
    specifications: { 'Dimensions': '1500x180x1020mm', 'IP Level': '44' }
  },
  {
    id: '601',
    categoryId: 'swing-barrier',
    name: 'SB-SPL-310',
    shortDescription: 'Cylindrical Swing Barrier.',
    fullDescription: `Compact cylindrical swing barrier. Ideal for aesthetic entrances.`,
    price: 'Request Quote',
    features: ['Pass Rate: 20-25 p/m', 'Operating Time: 0.2s', 'Stainless Steel Frame'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/SB-SPL-310.png',
    specifications: { 'Dimensions': '200*200*980mm', 'Pass Width': '600mm' }
  },
  {
    id: '603',
    categoryId: 'guard-patrol',
    name: 'Fingerprint Guard Patrol',
    shortDescription: 'Biometric Guard Tour System.',
    fullDescription: `Guard patrol system with fingerprint verification. Ensures guards are actually present.`,
    price: 'Request Quote',
    features: ['Storage: 60,000', 'Fingerprint Verification', 'Impact Detect'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/Fingerprint-Guard-Patrol-1.png',
    specifications: { 'Comm': 'USB', 'Battery': '3.7V Li-ion' }
  },
  {
    id: '605',
    categoryId: 'turnstiles',
    name: 'ET-1000',
    shortDescription: 'Tripod Turnstile.',
    fullDescription: `Standard tripod turnstile for access control. Compact and reliable.`,
    price: 'Request Quote',
    features: ['Throughput: 35 p/m', 'Bi-directional', 'IP44 Rating'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/ET1000.png',
    specifications: { 'Dimensions': '480x280x980mm', 'Pass Width': '520mm' }
  },
  {
    id: '607',
    categoryId: 'turnstiles',
    name: 'DT2000',
    shortDescription: 'Compact Tripod Turnstile.',
    fullDescription: `Space saving tripod turnstile. Stainless steel housing.`,
    price: 'Request Quote',
    features: ['Pass Rate: 20-25 p/m', 'MCBF: 3 Million', 'Semi-auto Mode'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/DT2000.png',
    specifications: { 'Dimensions': '200*200*980mm', 'Pass Width': '≤550mm' }
  },
  {
    id: '609',
    categoryId: 'turnstiles',
    name: 'HHT-TL-139',
    shortDescription: 'Half-Height Turnstile.',
    fullDescription: `Robust half-height turnstile for stadiums and factories. High durability.`,
    price: 'Request Quote',
    features: ['MCBF: 5 Million', 'Pass Rate: 30-35 p/m', 'Stainless Steel'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/HHT-TL-139.png',
    specifications: { 'Size': '1600*1400*1100mm', 'Pass Width': '600mm' }
  },
  {
    id: '611',
    categoryId: 'turnstiles',
    name: 'FHT-TL-249',
    shortDescription: 'Full Height Turnstile Double Door.',
    fullDescription: `Double lane full height turnstile for maximum security. Waterproof seal.`,
    price: 'Request Quote',
    features: ['Double Door', 'MCBF: 5 Million', 'Bi-directional'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/FHT-TL-249.png',
    specifications: { 'Frame': '304 Stainless Steel', 'Traffic Speed': '25 p/m' }
  },
  {
    id: '613',
    categoryId: 'turnstiles',
    name: 'FHT-TL-239',
    shortDescription: 'Full Height Turnstile Double Door.',
    fullDescription: `Secure double door full height turnstile. Ideal for perimeter control.`,
    price: 'Request Quote',
    features: ['Double Door', 'MCBF: 5 Million', 'Waterproof'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/FHT-TL-239.png',
    specifications: { 'Frame': '304 Stainless Steel', 'Traffic Speed': '25 p/m' }
  },
  {
    id: '615',
    categoryId: 'turnstiles',
    name: 'FHT-TL-149',
    shortDescription: 'Full Height Turnstile Single Door.',
    fullDescription: `Single lane full height turnstile. High security access control.`,
    price: 'Request Quote',
    features: ['Single Door', 'MCBF: 5 Million', 'IP44 Rating'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/FHT-TL-149.png',
    specifications: { 'Dimensions': '1630x1500x2310mm', 'Weight': '220kg' }
  },
  {
    id: '617',
    categoryId: 'turnstiles',
    name: 'FHT-TL-139',
    shortDescription: 'Full Height Turnstile Single Door.',
    fullDescription: `Durable single lane full height turnstile. Corrosion protected frame.`,
    price: 'Request Quote',
    features: ['Single Door', 'MCBF: 5 Million', 'Hydraulic Damper'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/FHT-TL-139.png',
    specifications: { 'Dimensions': '1630x1500x2310mm', 'Weight': '220kg' }
  },
  {
    id: '619',
    categoryId: 'turnstiles',
    name: 'FHT-TL-232',
    shortDescription: 'Full Height Turnstile Double.',
    fullDescription: `Double lane full height turnstile with mechanical locking. Precise movement.`,
    price: 'Request Quote',
    features: ['Double Lane', 'Anti-reverse', 'Fire Safety Mode'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/FHT-TL-232.png',
    specifications: { 'Dimensions': '2200x1500x2200mm', 'Pass Width': '650mm' }
  },
  {
    id: '621',
    categoryId: 'turnstiles',
    name: 'FHT-TL-132',
    shortDescription: 'Full Height Turnstile Single.',
    fullDescription: `Single lane full height turnstile. Secure and reliable.`,
    price: 'Request Quote',
    features: ['Single Lane', 'Anti-reverse', 'Fire Safety Mode'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/FHT-TL-132.png',
    specifications: { 'Dimensions': '1500x1450x2250mm', 'Pass Width': '650mm' }
  },
  {
    id: '623',
    categoryId: 'turnstiles',
    name: 'ETA-2000',
    shortDescription: 'Heavy Duty Tripod Turnstile.',
    fullDescription: `Automatic tripod turnstile for heavy duty use. 80kg arm tolerance.`,
    price: 'Request Quote',
    features: ['Heavy Duty', 'Full-Auto Mode', 'IP44 Rating'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/ETA-2000.png',
    specifications: { 'Dimensions': '1200x280x980mm', 'Pass Width': '520mm' }
  },
  {
    id: '625',
    categoryId: 'turnstiles',
    name: 'ETA-1000',
    shortDescription: 'Heavy Duty Automatic Turnstile.',
    fullDescription: `Automatic tripod turnstile. Supports RFID and Fingerprint integration.`,
    price: 'Request Quote',
    features: ['Automatic Arms', 'RFID/Fingerprint Support', 'IP44'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/ET1000-1.png',
    specifications: { 'Weight': '44kg', 'Throughput': '35 p/m' }
  },
  {
    id: '627',
    categoryId: 'turnstiles',
    name: 'ET-2000',
    shortDescription: 'One-Way Bridge Tripod Turnstile.',
    fullDescription: `Bridge type tripod turnstile. One-way or bi-directional operation.`,
    price: 'Request Quote',
    features: ['Bridge Design', 'Semi-automatic', '30,000 Users'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/ET2000-1.png',
    specifications: { 'Dimensions': '1200x280x980mm', 'Material': 'SUS 304' }
  },
  {
    id: '629',
    categoryId: 'turnstiles',
    name: 'ET-1200',
    shortDescription: 'Heavy Duty Tripod Turnstile.',
    fullDescription: `Compact heavy duty turnstile. Integrated access controller support.`,
    price: 'Request Quote',
    features: ['Heavy Duty', 'Integrated Controller', 'RFID/Fingerprint'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/ET1200.png',
    specifications: { 'Dimensions': '480x560x960mm', 'Weight': '60kg' }
  },
  {
    id: '632',
    categoryId: 'boom-barrier',
    name: 'BOOM BARRIER – BG-BDC-RL-100',
    shortDescription: 'Noise Less, Non Spring Boom Barrier.',
    fullDescription: `High performance DC brushless boom barrier. Adjustable speed and interchangeable arm direction.`,
    price: 'Request Quote',
    features: ['DC Brushless Motor', '1.5s-6s Speed', '6m Max Boom'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/BG-BDC-RL-100.png',
    specifications: { 'Motor Power': '160W', 'MCBF': '5 million' }
  },
  {
    id: '633',
    categoryId: 'tyre-killer',
    name: 'TK-300',
    shortDescription: 'Electromechanical Tyre Killer.',
    fullDescription: `Heavy duty tyre killer for high security vehicle access. 80T load capacity.`,
    price: 'Request Quote',
    features: ['80T Load', 'IP67 Rated', '3m Length'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/TK-300.png',
    specifications: { 'Spike Height': '150mm', 'Material': 'A3 Steel' }
  },
  {
    id: '635',
    categoryId: 'baggage-scanner',
    name: 'EBS-5030A',
    shortDescription: 'X-Ray Baggage Scanner 5030.',
    fullDescription: `Compact X-Ray scanner for bags and parcels. High penetration and resolution.`,
    price: 'Request Quote',
    features: ['Tunnel: 500x300mm', 'Conveyor Load: 100kg', 'Penetration: >8mm Steel'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/eBS-5030A.png',
    specifications: { 'Dimensions': '1500x770x1100mm', 'Anode Voltage': '80 KV' }
  },
  {
    id: '637',
    categoryId: 'metal-detector',
    name: 'D2401',
    shortDescription: 'Single Zone Metal Detector.',
    fullDescription: `Single zone walk-through metal detector. Detects ferrous metals.`,
    price: 'Request Quote',
    features: ['Single Zone', 'Adjustable Sensitivity', 'Ferrous Only'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/D2401.png',
    specifications: { 'Sensitivity': '≥200g Metal', 'Power': '12W' }
  },
  {
    id: '639',
    categoryId: 'metal-detector',
    name: 'D100S',
    shortDescription: 'Portable Handheld Metal Detector.',
    fullDescription: `Convenient handheld detector. Sound and light alarm.`,
    price: 'Request Quote',
    features: ['Handheld', 'Sound/Vibration Alarm', 'Rechargeable'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/D100S.png',
    specifications: { 'Dimensions': '401x85x45mm', 'Freq': '40KHz' }
  },
  {
    id: '641',
    categoryId: 'metal-detector',
    name: 'HM300',
    shortDescription: 'Handheld Metal Detector.',
    fullDescription: `Lightweight handheld detector. Detects ferrous metals.`,
    price: 'Request Quote',
    features: ['Handheld', 'Sound/Light Alarm', 'Ferrous Only'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/HM-300.png',
    specifications: { 'Dimensions': '340x140x30mm', 'Weight': '180g' }
  },
  {
    id: '643',
    categoryId: 'metal-detector',
    name: 'D9033',
    shortDescription: '33 Zone Metal Detector.',
    fullDescription: `33 zone high sensitivity walk-through detector. Precise detection.`,
    price: 'Request Quote',
    features: ['33 Zones', 'Ferrous Only', 'High Precision'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/D9033.png',
    specifications: { 'Sensitivity': '≥10g Metal', 'Power': '20W' }
  },
  {
    id: '645',
    categoryId: 'metal-detector',
    name: 'D9018',
    shortDescription: '18 Zone Metal Detector.',
    fullDescription: `18 zone walk-through detector for accurate location.`,
    price: 'Request Quote',
    features: ['18 Zones', 'Ferrous Only', 'Precision Detection'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/D9018.png',
    specifications: { 'Sensitivity': '≥10g Metal', 'Power': '20W' }
  },
  {
    id: '647',
    categoryId: 'metal-detector',
    name: 'D9006',
    shortDescription: '6 Zone Metal Detector.',
    fullDescription: `6 zone walk-through detector. Ferrous metal detection.`,
    price: 'Request Quote',
    features: ['6 Zones', 'Ferrous Only', 'Basic Security'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/D9006.png',
    specifications: { 'Sensitivity': '≥30g Metal', 'Power': '20W' }
  },
  {
    id: '649',
    categoryId: 'metal-detector',
    name: 'D2406',
    shortDescription: '6 Zone Metal Detector.',
    fullDescription: `6 zone detector with adjustable sensitivity. Ferrous detection.`,
    price: 'Request Quote',
    features: ['6 Zones', 'Adjustable Sensitivity', 'Ferrous Only'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/D2406.png',
    specifications: { 'Sensitivity': '≥200g Metal', 'Power': '12W' }
  },
  {
    id: '651',
    categoryId: 'metal-detector',
    name: 'HM100180',
    shortDescription: 'Super Scanner Metal Detector.',
    fullDescription: `High sensitivity handheld scanner. Rugged design.`,
    price: 'Request Quote',
    features: ['High Sensitivity', 'Rugged Design', 'Rechargeable'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/HM100180.png',
    specifications: { 'Dimensions': '415x85x45mm', 'Weight': '400g' }
  },
  {
    id: '653',
    categoryId: 'metal-detector',
    name: 'HM520PRO',
    shortDescription: 'Pro Handheld Metal Detector.',
    fullDescription: `Professional handheld detector with double alarm mode.`,
    price: 'Request Quote',
    features: ['Double Alarm', 'Light Indicator', 'Long Battery Life'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/HM520Pro.png',
    specifications: { 'Dimensions': '286x64x34mm', 'Weight': '230g' }
  },
  {
    id: '655',
    categoryId: 'metal-detector',
    name: 'D4006',
    shortDescription: 'Advanced 6 Zone Metal Detector.',
    fullDescription: `6 zone detector with 7 inch LCD touchscreen.`,
    price: 'Request Quote',
    features: ['6 Zones', '7-inch LCD Touchscreen', 'High Precision'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/D4006.png',
    specifications: { 'Dimensions': '2200x850x430mm', 'Input': 'AC 100-240V' }
  },
  {
    id: '657',
    categoryId: 'metal-detector',
    name: 'D518-63-IP65',
    shortDescription: 'IP65 63 Zone Metal Detector.',
    fullDescription: `Outdoor ready 63 zone metal detector. High weatherproof rating.`,
    price: 'Request Quote',
    features: ['63 Zones', 'IP65 Waterproof', 'Outdoor Use'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/D518-63-IP65-removebg-preview.png',
    specifications: { 'Passage Size': '2010x720x630mm', 'Weight': '46kg' }
  },
  {
    id: '659',
    categoryId: 'metal-detector',
    name: 'D330-33-IP65',
    shortDescription: 'IP65 33 Zone Metal Detector.',
    fullDescription: `Weatherproof 33 zone detector for accurate screening.`,
    price: 'Request Quote',
    features: ['33 Zones', 'IP65 Waterproof', 'Accurate'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/D330-33-IP65-removebg-preview.png',
    specifications: { 'Passage Size': '2007x720x446mm', 'Weight': '35kg' }
  },
  {
    id: '661',
    categoryId: 'metal-detector',
    name: 'D330-18-IP65',
    shortDescription: 'IP65 18 Zone Metal Detector.',
    fullDescription: `Weatherproof 18 zone detector.`,
    price: 'Request Quote',
    features: ['18 Zones', 'IP65 Waterproof', 'Outdoor Use'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/D330-18-IP65-removebg-preview.png',
    specifications: { 'Passage Size': '2007x720x446mm', 'Weight': '35kg' }
  },
  {
    id: '663',
    categoryId: 'metal-detector',
    name: 'D270-18-IP65',
    shortDescription: 'IP65 18 Zone Metal Detector.',
    fullDescription: `Compact weatherproof 18 zone detector.`,
    price: 'Request Quote',
    features: ['18 Zones', 'IP65 Waterproof', 'Compact'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/D270-removebg-preview.png',
    specifications: { 'Passage Size': '2017x720x349mm', 'Weight': '21kg' }
  },
  {
    id: '665',
    categoryId: 'metal-detector',
    name: 'D270-18-IP54',
    shortDescription: 'IP54 18 Zone Metal Detector.',
    fullDescription: `Standard 18 zone detector with IP54 rating.`,
    price: 'Request Quote',
    features: ['18 Zones', 'IP54 Rating', 'Standard Use'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/D270-1-removebg-preview.png',
    specifications: { 'Passage Size': '2017x720x349mm', 'Weight': '21kg' }
  },
  {
    id: '667',
    categoryId: 'metal-detector',
    name: 'D270-9-IP54',
    shortDescription: 'IP54 9 Zone Metal Detector.',
    fullDescription: `9 zone detector for basic screening needs.`,
    price: 'Request Quote',
    features: ['9 Zones', 'IP54 Rating', 'Basic Screening'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/D270-1-removebg-preview-1.png',
    specifications: { 'Passage Size': '2017x720x349mm', 'Weight': '21kg' }
  },
  {
    id: '669',
    categoryId: 'metal-detector',
    name: 'D468-6',
    shortDescription: '6 Zone Digital Panel.',
    fullDescription: `Single panel 6 zone digital metal detector.`,
    price: 'Request Quote',
    features: ['6 Zones', 'Single Panel', 'Digital'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/d468-6-1-removebg-preview.png',
    specifications: { 'External Size': '2203x580x117mm', 'Weight': '19kg' }
  },
  {
    id: '671',
    categoryId: 'metal-detector',
    name: 'D270-1-IP54',
    shortDescription: 'IP54 Single Zone Detector.',
    fullDescription: `Single zone detector with IP54 rating.`,
    price: 'Request Quote',
    features: ['Single Zone', 'IP54 Rating', 'Simple'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/D270-1-removebg-preview-1.png',
    specifications: { 'Passage Size': '2017x720x349mm', 'Weight': '21kg' }
  },
  {
    id: '672',
    categoryId: 'elevator-control',
    name: 'EC10-EX16',
    shortDescription: 'Elevator Control System.',
    fullDescription: `Secure elevator access control. EC10 panel + EX16 floor extension boards.`,
    price: 'Request Quote',
    features: ['10-Floor Control', 'Fingerprint/RFID', 'Expandable'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/EC10-EX16.png',
    specifications: { 'Relays': '10', 'Capacity': '3000 Fingerprints' }
  },
  {
    id: '674',
    categoryId: 'multi-door',
    name: 'C3 100',
    shortDescription: '1 Door Access Controller.',
    fullDescription: `IP-based 1 door access control panel. Supports 30,000 cards.`,
    price: 'Request Quote',
    features: ['1 Door', 'TCP/IP, RS485', '30,000 Users'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/EC10-EX16-1.png',
    specifications: { 'Inputs': '2', 'Outputs': '2' }
  },
  {
    id: '676',
    categoryId: 'multi-door',
    name: 'ESSL-ACCESS-8004',
    shortDescription: '4 Door Access Controller.',
    fullDescription: `Professional 4 door controller. TCP/IP communication.`,
    price: 'Request Quote',
    features: ['4 Doors', 'TCP/IP', 'Advanced Access Control'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/eSSL-Access-8004.png',
    specifications: { 'Capacity': '30,000 Users', 'Logs': '100,000' }
  },
  {
    id: '678',
    categoryId: 'multi-door',
    name: 'ESSL-ACCESS-8002',
    shortDescription: '2 Door Access Controller.',
    fullDescription: `Reliable 2 door access controller. 20,000 card capacity.`,
    price: 'Request Quote',
    features: ['2 Doors', 'TCP/IP', 'Fire Linkage Optional'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/eSSL-Access-8002.png',
    specifications: { 'Capacity': '20,000 Cards', 'Readers': '4' }
  },
  {
    id: '682',
    categoryId: 'multi-door',
    name: 'INBIO 460',
    shortDescription: 'Biometric 4 Door Controller.',
    fullDescription: `Biometric access controller for 4 doors. Supports fingerprint readers directly.`,
    price: 'Request Quote',
    features: ['4 Doors', 'Biometric Support', 'Anti-passback'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/inBio-460.png',
    specifications: { 'Fingerprint Capacity': '3000', 'Card Capacity': '30,000' }
  },
  {
    id: '684',
    categoryId: 'multi-door',
    name: 'INBIO 260',
    shortDescription: 'Biometric 2 Door Controller.',
    fullDescription: `Biometric access controller for 2 doors. Advanced access functions.`,
    price: 'Request Quote',
    features: ['2 Doors', 'Biometric Support', 'Interlock'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/inBio-260.png',
    specifications: { 'Fingerprint Capacity': '3000', 'Card Capacity': '30,000' }
  },
  {
    id: '686',
    categoryId: 'multi-door',
    name: 'C3-400',
    shortDescription: '4 Door RFID Controller.',
    fullDescription: `RFID access controller for 4 doors. Robust and feature rich.`,
    price: 'Request Quote',
    features: ['4 Doors', '30,000 Users', 'Web Monitoring'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/C3-400.png',
    specifications: { 'Readers': '12', 'Inputs': '12', 'Outputs': '8' }
  },
  {
    id: '688',
    categoryId: 'multi-door',
    name: 'C3 200',
    shortDescription: '2 Door RFID Controller.',
    fullDescription: `RFID access controller for 2 doors.`,
    price: 'Request Quote',
    features: ['2 Doors', '30,000 Users', 'TCP/IP'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/C3-200.png',
    specifications: { 'Readers': '4', 'Inputs': '6', 'Outputs': '4' }
  },
  {
    id: '690',
    categoryId: 'hotel-lock',
    name: 'ENERGY SAVING SWITCH',
    shortDescription: 'Hotel Energy Saver.',
    fullDescription: `Energy saving switch for hotel rooms. Mifare card activation.`,
    price: 'Request Quote',
    features: ['Mifare Card', '30A Load', '12s Delay'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/Energy_Saving_Switch.png',
    specifications: { 'Voltage': 'AC220V/110V', 'Power': '22W' }
  },
  {
    id: '692',
    categoryId: 'hotel-lock',
    name: 'RFID ENCODER AND UPDATER',
    shortDescription: 'Hotel Card Encoder.',
    fullDescription: `USB RFID encoder for issuing hotel cards.`,
    price: 'Request Quote',
    features: ['USB Interface', 'ISO 14443', 'Mifare Classic'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/RFID-Encoder.png',
    specifications: { 'Dimensions': '120.5x72x20.4mm', 'Weight': '140g' }
  },
  {
    id: '694',
    categoryId: 'hotel-lock',
    name: 'S70',
    shortDescription: 'Mifare 4K Card.',
    fullDescription: `Mifare 4K card for hotel applications. Large memory.`,
    price: 'Request Quote',
    features: ['4K Memory', '13.56 MHz', 'Contactless'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/S70.png',
    specifications: { 'Freq': '13.56 MHz', 'Transfer': '106 kbit/s' }
  },
  {
    id: '696',
    categoryId: 'hotel-lock',
    name: 'S50',
    shortDescription: 'Mifare 1K Card.',
    fullDescription: `Standard Mifare 1K card for guest access.`,
    price: 'Request Quote',
    features: ['1K Memory', '13.56 MHz', 'Contactless'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/S50.png',
    specifications: { 'Freq': '13.56 MHz', 'Transfer': '106 kbit/s' }
  },
  {
    id: '698',
    categoryId: 'hotel-lock',
    name: 'HANDHELD SERVICE UNIT',
    shortDescription: 'Hotel Lock Programmer.',
    fullDescription: `Handheld unit for programming and auditing hotel locks.`,
    price: 'Request Quote',
    features: ['Portable', 'Battery Powered', 'Audit Trail'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/HANDHELD-SERVICE-UNIT.png',
    specifications: { 'Dimensions': '155x80x28mm', 'Battery': '4x AA' }
  },
  {
    id: '700',
    categoryId: 'hotel-lock',
    name: 'HL-100',
    shortDescription: 'Stainless Steel Hotel Lock.',
    fullDescription: `Robust stainless steel hotel lock. RFID technology.`,
    price: 'Request Quote',
    features: ['SUS304 Stainless Steel', 'RFID', 'Fire Approved'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/HL100.png',
    specifications: { 'Power': '4x AA Batteries', 'Door Thickness': '35-80mm' }
  },
  {
    id: '702',
    categoryId: '7-series',
    name: 'EML600-7-2',
    shortDescription: '280KG Electromagnetic Lock.',
    fullDescription: `600lbs holding force EM lock with LED monitor.`,
    price: 'Request Quote',
    features: ['Holding Force: 280KG', 'LED Monitor', '12V DC'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/EML600-7-2-1.png',
    specifications: { 'Dimensions': '250x48x26mm', 'Current': '400mA' }
  },
  {
    id: '704',
    categoryId: '7-series',
    name: 'STRL50-2',
    shortDescription: 'EM Lock with Status LED.',
    fullDescription: `Reliable EM lock with bond sensor and status LED.`,
    price: 'Request Quote',
    features: ['Holding Force: 280KG', 'Bond Sensor', 'Anodized Housing'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/STRL50-2.png',
    specifications: { 'Dimensions': '250x48x26mm', 'Current': '400mA' }
  },
  {
    id: '706',
    categoryId: '7-series',
    name: 'BL99-7',
    shortDescription: 'Electric Rim Lock.',
    fullDescription: `Stainless steel electric rim lock for gates and doors.`,
    price: 'Request Quote',
    features: ['Stainless Steel', 'Key/Switch Unlock', '12V DC'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/BL99-7.png',
    specifications: { 'Size': '123x105x37mm', 'Current': '1.5-3A' }
  },
  {
    id: '708',
    categoryId: '7-series',
    name: 'BL-5-7',
    shortDescription: 'Electric Strike Lock.',
    fullDescription: `Electric strike with time delay and feedback.`,
    price: 'Request Quote',
    features: ['Fail Safe', 'Time Delay', 'Feedback Output'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/BL5-7.png',
    specifications: { 'Face Plate': '207x35x41mm', 'Voltage': '12VDC' }
  },
  {
    id: '710',
    categoryId: '7-series',
    name: 'STRL-240-7',
    shortDescription: 'Narrow Electric Strike.',
    fullDescription: `Electric strike for narrow wooden or metal doors.`,
    price: 'Request Quote',
    features: ['Narrow Design', 'Fail Secure', 'Zinc Alloy'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/STRL-240-7.png',
    specifications: { 'Dimensions': '150x34x28mm', 'Voltage': '12VDC' }
  },
  {
    id: '712',
    categoryId: '8-series',
    name: 'EML600-7-5',
    shortDescription: '5 Wire EM Lock.',
    fullDescription: `5 wire electromagnetic lock with feedback.`,
    price: 'Request Quote',
    features: ['5 Wires', '280KG Holding', '12V'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/EML600-7-5.png',
    specifications: { 'Dimensions': '250x48x27mm', 'Weight': '1.9KG' }
  },
  {
    id: '714',
    categoryId: '7-series',
    name: 'PUSH-7-SQ',
    shortDescription: 'Square Exit Button.',
    fullDescription: `Stainless steel square exit button.`,
    price: 'Request Quote',
    features: ['Stainless Steel', 'Square', 'NO/COM'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/7-Pushbutton-SQ.png',
    specifications: { 'Dimensions': '86x86mm', 'Rating': '3A@36VDC' }
  },
  {
    id: '716',
    categoryId: '7-series',
    name: 'PUSH-7-RC',
    shortDescription: 'Rectangular Exit Button.',
    fullDescription: `Stainless steel rectangular exit button.`,
    price: 'Request Quote',
    features: ['Stainless Steel', 'Rectangular', 'NO/COM'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/7-Pushbutton-RC.png',
    specifications: { 'Dimensions': '92x29mm', 'Rating': '3A@36VDC' }
  },
  {
    id: '718',
    categoryId: '7-series',
    name: 'NO TOUCH-SQ-7-K2',
    shortDescription: 'Square No Touch Sensor.',
    fullDescription: `Touchless exit button with adjustable range.`,
    price: 'Request Quote',
    features: ['No Touch', 'Adjustable Range', 'LED Indicator'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/7-No-Touch-K1-1.png',
    specifications: { 'Dimensions': '86x86x28mm', 'Input': '12V DC' }
  },
  {
    id: '720',
    categoryId: '7-series',
    name: 'NO TOUCH-7-K1',
    shortDescription: 'Rectangular No Touch Sensor.',
    fullDescription: `Touchless exit sensor.`,
    price: 'Request Quote',
    features: ['No Touch', 'Adjustable Range', 'LED Indicator'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/7-No-Touch-K1-1.png',
    specifications: { 'Dimensions': '115x70mm', 'Input': '12V DC' }
  },
  {
    id: '722',
    categoryId: '7-series',
    name: 'EML600-7-U',
    shortDescription: 'U Bracket for EM Lock.',
    fullDescription: `U bracket for installing 280kg EM locks on glass doors.`,
    price: 'Request Quote',
    features: ['Glass Door Mount', 'For 280kg Lock'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/u-bracket-7.png',
    specifications: { 'Type': 'U Bracket' }
  },
  {
    id: '724',
    categoryId: '7-series',
    name: 'EML600-7-ZL',
    shortDescription: 'ZL Bracket for EM Lock.',
    fullDescription: `Z & L bracket set for inward opening doors.`,
    price: 'Request Quote',
    features: ['Inward Door', 'For 280kg Lock'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/ZL-bracket.png',
    specifications: { 'Material': 'Aluminum' }
  },
  {
    id: '726',
    categoryId: '7-series',
    name: 'EML600D7-2',
    shortDescription: 'Double EM Lock.',
    fullDescription: `Double electromagnetic lock for double doors. 280kg x 2.`,
    price: 'Request Quote',
    features: ['Double Door', '280kg x 2', 'LED Monitor'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/EML600D7-2-removebg-preview.png',
    specifications: { 'Holding Force': '280KG x 2', 'Voltage': '12V DC' }
  },
  {
    id: '728',
    categoryId: '8-series',
    name: '8-EML600',
    shortDescription: '8-Series 600lbs Lock.',
    fullDescription: `Standard 8-series electromagnetic lock.`,
    price: 'Request Quote',
    features: ['280KG Holding', '12V'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/8-EML-600.png',
    specifications: { 'Dimensions': '250x48x27mm', 'Weight': '1.9KG' }
  },
  {
    id: '730',
    categoryId: '8-series',
    name: '8-BL99-U',
    shortDescription: 'U Bracket for Glass Door.',
    fullDescription: `Aluminum U bracket for frameless glass doors.`,
    price: 'Request Quote',
    features: ['Glass Door', 'High Strength Aluminum'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/8-BL99-U-removebg-preview.png',
    specifications: { 'Dimensions': '145.5x40x37.5mm' }
  },
  {
    id: '732',
    categoryId: '8-series',
    name: '8-PUSHBUTTON-SQ',
    shortDescription: 'Square Exit Button.',
    fullDescription: `Stainless steel square exit button.`,
    price: 'Request Quote',
    features: ['Stainless Steel', 'Square'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/7-Pushbutton-SQ.png',
    specifications: { 'Dimensions': '86x86x40mm', 'Voltage': '12V' }
  },
  {
    id: '733',
    categoryId: '8-series',
    name: '8-PUSHBUTTON-RC',
    shortDescription: 'Rectangular Exit Button.',
    fullDescription: `Stainless steel rectangular exit button.`,
    price: 'Request Quote',
    features: ['Stainless Steel', 'Rectangular'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/7-Pushbutton-RC.png',
    specifications: { 'Dimensions': '92x29mm', 'Rating': '3A' }
  },
  {
    id: '734',
    categoryId: '8-series',
    name: '8-MRC-80',
    shortDescription: 'Remote Control Switch.',
    fullDescription: `Wireless remote control switch kit.`,
    price: 'Request Quote',
    features: ['Wireless', '433.92MHz', '30m Range'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/8-MRC-80.png',
    specifications: { 'Voltage': '12V/24V', 'Output': 'Relay' }
  },
  {
    id: '736',
    categoryId: '8-series',
    name: '8-NOTOUCH-K2',
    shortDescription: 'Square No Touch Button.',
    fullDescription: `Square touchless exit button.`,
    price: 'Request Quote',
    features: ['No Touch', 'Adjustable Range', 'LED'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/8-NoTouch-K2.png',
    specifications: { 'Dimensions': '86x86x16mm', 'Input': '12-24V' }
  },
  {
    id: '738',
    categoryId: '8-series',
    name: '8-NOTOUCH-K1',
    shortDescription: 'Rectangular No Touch Button.',
    fullDescription: `Rectangular touchless exit button.`,
    price: 'Request Quote',
    features: ['No Touch', 'Adjustable Range', 'LED'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/7-No-Touch-K1-1-2.png',
    specifications: { 'Dimensions': '115x70x16mm', 'Input': '12-24V' }
  },
  {
    id: '740',
    categoryId: '8-series',
    name: '8-BL39-LEFT',
    shortDescription: 'Electric Lock Left.',
    fullDescription: `Electric lock for left hand doors.`,
    price: 'Request Quote',
    features: ['Left Hand', '12V DC'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/BL99-7.png',
    specifications: { 'Dimensions': '148x43x39mm' }
  },
  {
    id: '741',
    categoryId: '8-series',
    name: '8-BL39-RIGHT',
    shortDescription: 'Electric Lock Right.',
    fullDescription: `Electric lock for right hand doors.`,
    price: 'Request Quote',
    features: ['Right Hand', '12V DC'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/BL99-7.png',
    specifications: { 'Dimensions': '148x43x39mm' }
  },
  {
    id: '742',
    categoryId: '8-series',
    name: '8-BL-2',
    shortDescription: 'Electric Bolt Lock.',
    fullDescription: `Electric drop bolt lock.`,
    price: 'Request Quote',
    features: ['Drop Bolt', 'Fail Safe'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2024/09/8-BL-2-removebg-preview.png',
    specifications: { 'Dimensions': '200x34x42mm', 'Power': '12V' }
  },
  {
    id: '750',
    categoryId: 'face',
    name: 'Face - Aiface-Orcus',
    shortDescription: 'Dual Core Face Terminal.',
    fullDescription: `2.4 inch screen facial terminal. Dual core CPU.`,
    price: 'Request Quote',
    features: ['Dual Core CPU', 'Binocular Camera', 'Linux'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2025/04/1.webp',
    specifications: { 'Screen': '2.4 inch', 'RAM': '512MB' }
  },
  {
    id: '751',
    categoryId: 'face',
    name: 'Face - AiFace-Arion',
    shortDescription: '5-inch Face & Fingerprint.',
    fullDescription: `Multi-biometric terminal with 5 inch screen.`,
    price: 'Request Quote',
    features: ['Face/Finger/Card', '5-inch Screen', 'Linux'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2025/04/SpeedFace-M4-Visible-Light-Facial-and-Palm-Recognition-Terminal.jpg',
    specifications: { 'Display': '5-Inch', 'Camera': '2MP WDR' }
  },
  {
    id: '756',
    categoryId: 'face',
    name: 'Face - AiFace Arion+HID',
    shortDescription: 'Face & HID Card Terminal.',
    fullDescription: `Face recognition with HID card support.`,
    price: 'Request Quote',
    features: ['HID Card Support', 'Face/Finger', 'Linux'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2025/04/2.jpg',
    specifications: { 'Display': '5-Inch', 'Camera': '2MP WDR' }
  },
  {
    id: '758',
    categoryId: 'face',
    name: 'Face - AiFace-Mars+HID',
    shortDescription: 'Visible Light Face + HID.',
    fullDescription: `Visible light facial recognition with HID support.`,
    price: 'Request Quote',
    features: ['HID Card', 'Visible Light', 'Anti-spoofing'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2025/04/2.jpg',
    specifications: { 'Verification': 'Face/HID/Pwd' }
  },
  {
    id: '759',
    categoryId: 'face',
    name: 'Face - Aiface ERIS',
    shortDescription: '4-inch Face & Finger Terminal.',
    fullDescription: `Compact 4-inch terminal for face and fingerprint access.`,
    price: 'Request Quote',
    features: ['4-inch Touch', 'Face/Finger', '3000 Users'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2025/04/3.webp',
    specifications: { 'Display': '4-inch', 'Camera': '2MP' }
  },
  {
    id: '761',
    categoryId: 'face',
    name: 'Face - Aiface ERIS+HID',
    shortDescription: '4-inch Face & HID Terminal.',
    fullDescription: `ERIS model with HID card support.`,
    price: 'Request Quote',
    features: ['HID Card', '4-inch Touch', 'Face/Finger'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2025/04/4.webp',
    specifications: { 'Display': '4-inch', 'Camera': '2MP' }
  },
  {
    id: '763',
    categoryId: 'face',
    name: 'Face - Aiface Mars+QR',
    shortDescription: 'Face & QR Code Terminal.',
    fullDescription: `Advanced terminal with Face and QR code scanning capabilities.`,
    price: 'Request Quote',
    features: ['QR Code', 'Face/Card', '5-inch Screen'],
    imageUrl: 'https://tsttechnologies.com/wp-content/uploads/2025/04/5.webp',
    specifications: { 'Display': '5-Inch', 'CPU': '900MHz Dual Core' }
  }
];
